name: Workflow Validate
on:
  workflow_call:
  workflow_dispatch:
jobs:
  run-sushi-tests_gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:      
          path: source
      - uses: ansforge/cisis-action-validate-exemple
        with:      
          repo_ig: "./source"   
