name: Workflow Validate
on:
  workflow_call:
  push:
  workflow_dispatch:
jobs:
  run-sushi-tests_gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:      
          path: source
      - uses: M-priour/cisis-action-validate-exemple@main
        with:      
          repo_ig: "./source"   
